### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/datafable.github.io#11]
* [ ] Remove unused images
* [ ] Choose resolution for bg image
* [ ] Scale font-size of h2 with media queries
* [ ] Increase font-size of h4
* [ ] Review menu
* [ ] Finish services
* [ ] Update portofolio
* [ ] Combine team and contact
