### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/datafable.github.io#3]
- [x] add Google site verification
- [x] add Google Analytics
- [x] add meta description
- [x] add favicon
- [x] add header links
- [x] add contact us link
- [x] add footer
- [x] minimum thumbnail image width = `735px`
- [x] add better portfolio titles
- [x] CDN for bootstrap
- [x] CDN for jQuery
- [x] CDN for font awesome
- [x] Test other browsers
- [x] Test all links
- [x] Ease transition for anchors -> #7
- [x] Decide on link colours (and portfolio hoover)
- [x] Open links in new window?
- [x] Add email template -> #8
- [x] Review text and titles
- [x] No link on brand
- [x] Anchors should not jump under title
- [x] Need mail address
- [x] We offer expertise in data visualization and publication -> rename (see #4)
- [x] Remove Flemish Parliament
- [x] Bird migration detected by weather radars -> rename
- [x] Publishing biodiversity data collected by scuba divers -> link to dataset
- [x] Blue hoover for portfolio elements
- [x] Footer elements to left
- [x] We love [open source and open data](..).
- [x] Email, then twitter for team members
